//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-runtime-gvisor/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*GVisorConfiguration)(nil), (*config.GVisorConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GVisorConfiguration_To_config_GVisorConfiguration(a.(*GVisorConfiguration), b.(*config.GVisorConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GVisorConfiguration)(nil), (*GVisorConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GVisorConfiguration_To_v1alpha1_GVisorConfiguration(a.(*config.GVisorConfiguration), b.(*GVisorConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_GVisorConfiguration_To_config_GVisorConfiguration(in *GVisorConfiguration, out *config.GVisorConfiguration, s conversion.Scope) error {
	out.ConfigFlags = (*map[string]string)(unsafe.Pointer(in.ConfigFlags))
	out.TestImageTag = (*string)(unsafe.Pointer(in.TestImageTag))
	return nil
}

// Convert_v1alpha1_GVisorConfiguration_To_config_GVisorConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_GVisorConfiguration_To_config_GVisorConfiguration(in *GVisorConfiguration, out *config.GVisorConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_GVisorConfiguration_To_config_GVisorConfiguration(in, out, s)
}

func autoConvert_config_GVisorConfiguration_To_v1alpha1_GVisorConfiguration(in *config.GVisorConfiguration, out *GVisorConfiguration, s conversion.Scope) error {
	out.ConfigFlags = (*map[string]string)(unsafe.Pointer(in.ConfigFlags))
	out.TestImageTag = (*string)(unsafe.Pointer(in.TestImageTag))
	return nil
}

// Convert_config_GVisorConfiguration_To_v1alpha1_GVisorConfiguration is an autogenerated conversion function.
func Convert_config_GVisorConfiguration_To_v1alpha1_GVisorConfiguration(in *config.GVisorConfiguration, out *GVisorConfiguration, s conversion.Scope) error {
	return autoConvert_config_GVisorConfiguration_To_v1alpha1_GVisorConfiguration(in, out, s)
}
