{{- if not .Values.pspDisabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: gvisor
  namespace: kube-system
spec:
  privileged: true
  volumes:
    - 'configMap'
    - 'secret'
    - 'hostPath'
  hostNetwork: false
  hostIPC: true
  hostPID: true
  allowedHostPaths:
    - pathPrefix: /
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
{{- end }}
