name: Create Upgrade-Pull-Requests
on:
  schedule:
    - cron: '0 09 * * MON' # run every monday
  workflow_dispatch:

jobs:
  bump-gvisor-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gardener/cc-utils/.github/actions/install-gardener-gha-libs@master
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.GARDENER_GITHUB_ACTIONS_APP_ID }}
          private-key: ${{ secrets.GARDENER_GITHUB_ACTIONS_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: bump-gvisor-version
        shell: bash
        run: |
          set -eu
          .ci/check_and_bump_gvisor_version.py
